# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "alloy_smith_repl"
version = "0.1.0"
authors = ["theochupp <tclchiam@gmail.com>"]
edition = "2018"

[dependencies]
alloy_syntax = { path = "../../compiler/syntax" }

[dev-dependencies]
expect-test = "1.3"
pretty_assertions = "1.2.1"
test_source = { path = "../../test_source" }
