[workspace]
members = [
    "compiler",
    "compiler/ast",
    "compiler/diagnostics",
    "compiler/hir_parent/hir",
    "compiler/hir_parent/hir_resolved",
    "compiler/hir_parent/hir_ty",
    "compiler/lexer",
    "compiler/parser",
    "compiler/project",
    "compiler/scope",
    "compiler/syntax",
    "compiler/test_harness",
    "compiler/workspace",
    "smith/repl",
]

[workspace.dependencies]
ariadne = "0.6"
camino = "1.2.2"
expect-test = "1.5"
itertools = "0.14"
la-arena = "0.3"
maplit = "1.0"
non-empty-vec = "0.2"
num-derive = "0.4"
num-traits = "0.2"
ordered-float = "5.1"
pretty_assertions = "1.4"
rowan = "0.16"
rustc-hash = "1.1"
salsa = "0.26"
serde = "1.0"
text-size = "1.1"
toml = "1.0"
url = "2.5.8"
walkdir = "2"

