[workspace]
members = [
    "compiler",
    "compiler/ast",
    "compiler/lexer",
    "compiler/parser",
    "compiler/rowan",
    "compiler/rowan/lexer",
    "compiler/rowan/parser",
    "compiler/rowan/syntax",
    "smith/repl",
    "test_source",
]
