[workspace]
members = [
    "compiler",
    "compiler/ast",
    "compiler/hir",
    "compiler/lexer",
    "compiler/parser",
    "compiler/project",
    "compiler/scope",
    "compiler/syntax",
    "compiler/test_harness",
    "smith/repl",
]
