[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["format"]

[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test"
]

[tasks.cov]
description = "Generate code coverage report in HTML format"
workspace = false
command = "cargo"
dependencies = ["cov-clean"]
args = ["llvm-cov", "--workspace", "--html", "--ignore-run-fail", "--open"]

[tasks.cov-clean]
description = "Clean coverage artifacts"
workspace = false
command = "cargo"
args = ["llvm-cov", "clean", "--workspace"]
