# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "alloy_syntax"
version = "0.1.0"
authors = ["theochupp <tclchiam@gmail.com>"]
edition = "2018"

[dependencies]
drop_bomb = "0.1.5"
non-empty-vec = "0.2"
maplit = "1.0"
rowan = "0.15"
logos = "0.12"
num-derive = "0.3"
num-traits = "0.2"

[dev-dependencies]
expect-test = "1.3"
pretty_assertions = "1.2.1"
test_source = { path = "../../test_source" }
