[package]
name = "alloy_project"
version = "0.1.0"
authors = ["theochupp <tclchiam@gmail.com>"]
edition = "2018"

[dependencies]
rustc-hash = "1.1"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
