# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "alloy_hir_resolved"
version = "0.1.0"
authors = ["theochupp <tclchiam@gmail.com>"]
edition = "2018"

[dependencies]
alloy_hir = { path = "../hir" }
alloy_scope = {path = "../../scope"}
alloy_workspace = {path = "../../workspace"}
la-arena = { workspace = true }
non-empty-vec = { workspace = true }
salsa = { workspace = true }
text-size = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
alloy_ast = { path = "../../ast" }
alloy_project = { path = "../../project" }
alloy_test_harness = {path = "../../test_harness"}
camino = { workspace = true }
