# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "alloy_hir_typed"
version = "0.1.0"
authors = ["theochupp <tclchiam@gmail.com>"]
edition = "2018"

[dependencies]
alloy_ast = { path = "../ast" }
alloy_hir = {path = "../hir"}
alloy_workspace = {path = "../workspace"}
alloy_scope = { path = "../scope" }
la-arena = { workspace = true }
rustc-hash = { workspace = true }
non-empty-vec = { workspace = true }
salsa = { workspace = true }

[dev-dependencies]
alloy_parser = {path = "../parser"}
alloy_test_harness = {path = "../test_harness"}
alloy_workspace = {path = "../workspace"}
