# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "alloy_parser"
version = "0.1.0"
authors = ["theochupp <tclchiam@gmail.com>"]
edition = "2018"

[dependencies]
alloy_ast = { path = "../ast" }
alloy_lexer = { path = "../lexer" }
codespan-reporting = "0.11"
improved_slice_patterns = "2.0"
itertools = "0.10"
peekmore = "1.0"

[dev-dependencies]
pretty_assertions = "1.0.0"
test_source = { path = "../../test_source" }
