[package]
name = "alloy_scope"
version = "0.1.0"
authors = ["theochupp <tclchiam@gmail.com>"]
edition = "2018"

[dependencies]
la-arena = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
