# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "alloy_hir_def"
version = "0.1.0"
authors = ["theochupp <tclchiam@gmail.com>"]
edition = "2018"

[dependencies]
alloy_ast = { workspace = true }
alloy_diagnostics = { workspace = true }
alloy_parser = { workspace = true }
alloy_scope = { workspace = true }
alloy_syntax = { workspace = true }
alloy_workspace = { workspace = true }

[dev-dependencies]
alloy_parser = { workspace = true }
alloy_project = { workspace = true }
alloy_test_harness = { workspace = true }
camino = { workspace = true }
